import { FunctionComponent, PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import { NewTodoForm } from './components/new-todo-form'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface LayoutProps extends PropsWithChildren {}

const Layout: FunctionComponent<LayoutProps> = ({ children }) => {
  return (
    <>
      <div className='p-5 flex flex-col gap-4'>
        <div className='mt-5'>
          <NewTodoForm />
        </div>
        {children}
      </div>
    </>
  )
}

export default Layout
